### ISSUE TITLE
확인 부탁합니다

### ISSUE THREAD

**Issue by Iinsnad** [lewisleedev/thecampy#7]
예시처럼 작성하였을때
my_soldier = thecampy.Soldier('이름', '생일', '입영일자')

예외가 발생했습니다. KeyError
'listResult'

이 값만 읽어옵니다.

`{'resultCd': '9998', 'resultMsg': '육군카페만 지원 됩니다'}`

form에서
```
  "trainUnitTypeCd": '',
  "trainUnitCd": '',
  "grpCd": ''
```
추가하여 
```
def get_soldier(self, soldier):
        self.enforce_login()
        form = {
            "name": soldier.name,
            "enterDate": soldier.enlist_date,
            "birth": soldier.bday,
            "trainUnitTypeCd": '',
            "trainUnitCd": '',
            "grpCd": ''
        }
```
위와같이 작성시 잘 작동하였습니다
제 상황에서만 발생하는 오류일수도 있는데 체크한번 부탁드립니다 감사합니다

**Comment by shlewislee** [comment]
버그 재현을 위해 테스트해본결과 listResult KeyError 재현 확인되었습니다. 그러나

```
def get_soldier(self, soldier):
        self.enforce_login()
        form = {
            "name": soldier.name,
            "enterDate": soldier.enlist_date,
            "birth": soldier.bday,
            "trainUnitTypeCd": '',
            "trainUnitCd": '',
            "grpCd": ''
        }
```
이 수정 후에도 육군카페만 지원된다는 오류가 발생했습니다. grpCd에 육군코드를 임의로 넣어준 결과,

```
{'resultCd': '9996', 'resultMsg': '입영부대를 입력하지 않으셨습니다.'}
```
라는 오류를 return받았습니다. #6 PR 이후 변경된것인지, 이후 trainUnitCd에 부대 코드를 입력해주니 입영부대 오류는 사라졌습니다. 테스트한 신원이 카페 개설이 안돼있는 상태라(훈련소 수료 후) 이후 테스트는 어렵습니다만, 부대 코드가 필요한 것 같습니다. 기존에도 부대코드는 사용하는 곳이 없던걸 감안하면, 더캠프에서 추가로 업데이트가 이루어진 것 같습니다. 추가하신 세 항목을 공란으로 두어도 정상적으로 작동하는건가요?

**Comment by shlewislee** [comment]
일단 [e3b1ea1](https://github.com/lewisleedev/thecampy/commit/e3b1ea1d72aaf3c00f005266e580a8413b0321f3) 커밋에서 먼저 resultCd를 r.json()['listResult']보다 먼저 확인하도록 수정했습니다. 추후 부대코드관련 테스트가 이루어지면 오류 수정하겠습니다.

**Comment by Iinsnad** [comment]
테스트 결과

"trainUnitCd": '',
 "grpCd": ''

이 두개의 코드만 필요하였습니다.

[예외가 발생했습니다. KeyError
'listResult]'
이 오류가 발생한 이유가 "grpCd;" 값을 입력하지 않아서 발생한것 같습니다.

"trainUnitTypeCd" 값의 경우 테스트를 통해 필요가 없음을 확인하였습니다.

**Comment by shlewislee** [comment]
테스트 결과 trainUnitCd와 grpCd 모두 값이 없으면 에러가 일어났습니다. grdCd는 육군 코드로 고정, trainUnitCd는 기존의 unit_code를 불러오는 것으로 수정했습니다. 이제 부대코드가 없으면 작동하지 않습니다.

458e6eff7dcbe928d8f17fde530d5d851878fcc3
